In [1]:
import numpy as np
import matplotlib.pyplot as plt

## A Single Neuron

In [6]:
inputs = [1,2,3,2.5]
weights = [0.2,0.8,-0.5,1.0]
bias = 2

print(inputs)
print(weights)
print(bias)

[1, 2, 3, 2.5]
[0.2, 0.8, -0.5, 1.0]
2


In [8]:
output = (inputs[0] * weights[0] +
          inputs[1] * weights[1] +
          inputs[2] * weights[2] +
          inputs[3] * weights[3] + bias)
output

4.8

## A Layer of Neurons

In [9]:
inputs = [1,2,3,2.5]

weights_1 = [0.2,0.8,-0.5,1.0]
weights_2 = [0.5,-0.91,0.26,-0.5]
weights_3 = [-0.26,-0.27,0.17,0.87]


bias_1 = 2
bias_2 = 3
bias_3 = 0.5

In [11]:
outputs = [
    # Neuron 1
    inputs[0] * weights_1[0] +
    inputs[1] * weights_1[1] +
    inputs[2] * weights_1[2] +
    inputs[3] * weights_1[3] + bias_1,
    
    # Neuron 2
    inputs[0] * weights_2[0] +
    inputs[1] * weights_2[1] +
    inputs[2] * weights_2[2] +
    inputs[3] * weights_2[3] + bias_2,
    
    # Neuron 3
    inputs[0] * weights_3[0] +
    inputs[1] * weights_3[1] +
    inputs[2] * weights_3[2] +
    inputs[3] * weights_3[3] + bias_3
]

outputs

[4.8, 1.21, 2.385]

In [12]:
inputs = [1,2,3,2.5]

weights = [[0.2,0.8,-0.5,1.0],
           [0.5,-0.91,0.26,-0.5],
           [-0.26,-0.27,0.17,0.87]]

biases = [2,3,0.5]

In [13]:
layer_outputs = []

for neuron_weights, neuron_bias in zip(weights, biases):
    neuron_output = 0
    
    for n_input, weight in zip(inputs, neuron_weights):
        neuron_output += n_input * weight
    
    neuron_output += neuron_bias
    
    layer_outputs.append(neuron_output)
    
layer_outputs

[4.8, 1.21, 2.385]

## Tensors, Arrays and Vectors 

In [15]:
l = [1,5,6,2]
lol = [[1,5,6,2],
      [3,2,1,3]]
lolol = [[[1,5,6,2],
          [3,2,1,3]],
         [[5,2,1,2],
          [6,4,8,4]],
         [[2,8,5,3],
          [1,1,9,4]]]

lolol

[[[1, 5, 6, 2], [3, 2, 1, 3]],
 [[5, 2, 1, 2], [6, 4, 8, 4]],
 [[2, 8, 5, 3], [1, 1, 9, 4]]]

In [16]:
another_list_of_lists = [[4,2,3], [5,1]]

In [17]:
list_matrix_array = [[4,2], [5,1],[8,2]]

## Dot Product and Vector Addition

In [18]:
a = [1,2,3]
b = [2,3,4]

In [19]:
dot_product = a[0]*b[0] + a[1]*b[1] + a[2]*b[2]
dot_product

20

## A Single Neuron with NumPy

In [23]:
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0

outputs = np.dot(weights, inputs) + bias
outputs

4.8

## A Layer of Neurons with NumPy

In [24]:
inputs = [1,2,3,2.5]

weights = [[0.2,0.8,-0.5,1.0],
           [0.5,-0.91,0.26,-0.5],
           [-0.26,-0.27,0.17,0.87]]

biases = [2,3,0.5]

In [31]:
layer_outputs = np.dot(weights, inputs) + biases
layer_outputs

array([4.8  , 1.21 , 2.385])

In [32]:
layer_outputs = np.dot(inputs, weights) + biases
layer_outputs

ValueError: shapes (4,) and (3,4) not aligned: 4 (dim 0) != 3 (dim 0)

In [35]:
layer_outputs = np.dot(inputs, np.array(weights).T) + biases
layer_outputs

array([4.8  , 1.21 , 2.385])

## Transposition of the Matrix Product

In [33]:
a = [1,2,3]
b = [2,3,4]

a = np.array([a])
b = np.array([b])

print(np.dot(a,b.T))

[[20]]


## A Layer of Neurons & Batch of Data w/ NumPy

In [36]:
inputs = [[1.0,2.0,3.0,2.5],
          [2.0,5.0,-1.0,2.0],
          [-1.5,2.7,-0.5,-0.8]]

weights = [[0.2,0.8,-0.5,1.0],
           [0.5,-0.91,0.26,-0.5],
           [-0.26,-0.27,0.17,0.87]]

biases = [2,3,0.5]

outputs = np.dot(inputs, np.array(weights).T) + biases
outputs

array([[ 4.8  ,  1.21 ,  2.385],
       [ 8.9  , -1.81 ,  0.2  ],
       [ 3.31 ,  0.063, -0.62 ]])

In [37]:
np.dot(inputs, np.array(weights).T)

array([[ 2.8  , -1.79 ,  1.885],
       [ 6.9  , -4.81 , -0.3  ],
       [ 1.31 , -2.937, -1.12 ]])

In [38]:
np.dot(inputs, np.array(weights).T).shape

(3, 3)